### ISSUE TITLE
Need to document the dependency on "Optimization Toolbox" and "Global Optimization Toolbox" MATLAB Packages

### ISSUE THREAD

**Issue by dcolli23** [Campbell-Muscle-Lab/MATMyoSim#3]
# Description

When running the "Twitch 1" demo, I encountered some errors due to me not installing the "Global Optimization Toolbox" (which has a dependency on the "Optimization Toolbox" as well).

This was remedied by running the MATLAB installer again installing these packages.

**Comment by kenatcampbellmusclelab** [comment]
Fixed
