### ISSUE TITLE
Update docs to show how to install from GitHub repo

### ISSUE THREAD

**Issue by kenatcampbellmusclelab** [Campbell-Muscle-Lab/MATMyoSim#7]
@dcolli23  - can you add docs to show how to install from GitHubb repo. The FiberSim project has something close. You can also point people to the howtos_GitHub video I made. I have opened up all the howtos repos to be public-facing.

**Comment by dcolli23** [comment]
@kenatcampbellmusclelab Sure thing.

**Comment by dcolli23** [comment]
This was addressed with 54eefa984294e03e3d4b7ea2b9a34fcfb1e63667.
