### ISSUE TITLE
Myosin states and distributions not saved when running 4state_with_SRX

### ISSUE THREAD

**Issue by akschroer** [Campbell-Muscle-Lab/MATMyoSim#8]
Not sure why it is not able to display/save these values while it is still able to calculate, display and save force and actin availability.
![trying 4state_with_SRX](https://user-images.githubusercontent.com/26775401/86303136-c1099600-bbbf-11ea-986e-2d5da29ff246.jpg)
Thanks!

**Comment by kenatcampbellmusclelab** [comment]
@akschroer This was a bug introduced by me trying to fix something else. Should be fixed now.
